"""Tests for npm lockfile parsers."""

from __future__ import annotations

import json
import textwrap

from dep_audit.lockfiles_pkg import parse_from_content, parse_npm
from dep_audit.lockfiles_pkg.npm import (
    _parse_package_json_content,
    _parse_package_lock_json_content,
    _parse_pnpm_lock_yaml_content,
    _parse_yarn_lock_content,
)

# ---------------------------------------------------------------------------
# package-lock.json v2/v3
# ---------------------------------------------------------------------------

PACKAGE_JSON = json.dumps({
    "name": "my-app",
    "dependencies": {
        "express": "^4.18.0",
        "node-fetch": "^3.0.0",
    },
    "devDependencies": {
        "jest": "^29.0.0",
    },
})

PACKAGE_LOCK_V2 = json.dumps({
    "name": "my-app",
    "lockfileVersion": 2,
    "packages": {
        "": {"name": "my-app"},
        "node_modules/express": {"version": "4.18.2"},
        "node_modules/node-fetch": {"version": "3.3.1"},
        "node_modules/jest": {"version": "29.7.0", "dev": True},
        "node_modules/body-parser": {"version": "1.20.2"},
        "node_modules/@types/node": {"version": "20.10.0", "dev": True},
    },
})


def test_parse_package_lock_v2():
    result = _parse_package_lock_json_content(PACKAGE_LOCK_V2, PACKAGE_JSON, False)
    assert result.ecosystem == "npm"
    names = {d.name for d in result.deps}
    assert "express" in names
    assert "node-fetch" in names
    assert "body-parser" in names
    # dev deps excluded
    assert "jest" not in names
    assert "@types/node" not in names


def test_parse_package_lock_v2_with_dev():
    result = _parse_package_lock_json_content(PACKAGE_LOCK_V2, PACKAGE_JSON, True)
    names = {d.name for d in result.deps}
    assert "jest" in names
    assert "@types/node" in names
    assert "express" in names


def test_parse_package_lock_v2_direct_detection():
    result = _parse_package_lock_json_content(PACKAGE_LOCK_V2, PACKAGE_JSON, False)
    dep_map = {d.name: d for d in result.deps}
    assert dep_map["express"].is_direct is True
    assert dep_map["node-fetch"].is_direct is True
    assert dep_map["body-parser"].is_direct is False


# ---------------------------------------------------------------------------
# package-lock.json v1
# ---------------------------------------------------------------------------

PACKAGE_LOCK_V1 = json.dumps({
    "name": "my-app",
    "lockfileVersion": 1,
    "dependencies": {
        "express": {
            "version": "4.18.2",
            "dependencies": {
                "body-parser": {"version": "1.20.2"},
            },
        },
        "node-fetch": {"version": "3.3.1"},
        "jest": {"version": "29.7.0", "dev": True},
    },
})


def test_parse_package_lock_v1():
    result = _parse_package_lock_json_content(PACKAGE_LOCK_V1, PACKAGE_JSON, False)
    assert result.ecosystem == "npm"
    names = {d.name for d in result.deps}
    assert "express" in names
    assert "node-fetch" in names
    assert "body-parser" in names
    assert "jest" not in names


def test_parse_package_lock_v1_direct():
    result = _parse_package_lock_json_content(PACKAGE_LOCK_V1, PACKAGE_JSON, False)
    dep_map = {d.name: d for d in result.deps}
    assert dep_map["express"].is_direct is True
    assert dep_map["body-parser"].is_direct is False


# ---------------------------------------------------------------------------
# yarn.lock v1
# ---------------------------------------------------------------------------

YARN_LOCK = textwrap.dedent("""\
    # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
    # yarn lockfile v1

    express@^4.18.0:
      version "4.18.2"
      resolved "https://registry.yarnpkg.com/express/-/express-4.18.2.tgz"

    "node-fetch@^3.0.0":
      version "3.3.1"
      resolved "https://registry.yarnpkg.com/node-fetch/-/node-fetch-3.3.1.tgz"

    body-parser@1.20.2:
      version "1.20.2"
      resolved "https://registry.yarnpkg.com/body-parser/-/body-parser-1.20.2.tgz"

    "@types/node@^20.0.0":
      version "20.10.0"
      resolved "https://registry.yarnpkg.com/@types/node/-/node-20.10.0.tgz"
""")


def test_parse_yarn_lock_v1():
    result = _parse_yarn_lock_content(YARN_LOCK, PACKAGE_JSON, False)
    assert result.ecosystem == "npm"
    names = {d.name for d in result.deps}
    assert "express" in names
    assert "node-fetch" in names
    assert "body-parser" in names
    assert "@types/node" in names


def test_parse_yarn_lock_direct():
    result = _parse_yarn_lock_content(YARN_LOCK, PACKAGE_JSON, False)
    dep_map = {d.name: d for d in result.deps}
    assert dep_map["express"].is_direct is True
    assert dep_map["body-parser"].is_direct is False


# ---------------------------------------------------------------------------
# pnpm-lock.yaml
# ---------------------------------------------------------------------------

PNPM_LOCK = textwrap.dedent("""\
    lockfileVersion: '6.0'

    dependencies:
      express:
        specifier: ^4.18.0
        version: 4.18.2
      node-fetch:
        specifier: ^3.0.0
        version: 3.3.1

    devDependencies:
      jest:
        specifier: ^29.0.0
        version: 29.7.0

    packages:

      /express@4.18.2:
        resolution: {integrity: sha512-abc}
        dependencies:
          body-parser: 1.20.2

      /node-fetch@3.3.1:
        resolution: {integrity: sha512-def}

      /body-parser@1.20.2:
        resolution: {integrity: sha512-ghi}

      /jest@29.7.0:
        resolution: {integrity: sha512-jkl}
        dev: true

      /@types/node@20.10.0:
        resolution: {integrity: sha512-mno}
        dev: true
""")


def test_parse_pnpm_lock():
    result = _parse_pnpm_lock_yaml_content(PNPM_LOCK, PACKAGE_JSON, False)
    assert result.ecosystem == "npm"
    names = {d.name for d in result.deps}
    assert "express" in names
    assert "node-fetch" in names
    assert "body-parser" in names
    # dev deps excluded
    assert "jest" not in names
    assert "@types/node" not in names


def test_parse_pnpm_lock_with_dev():
    result = _parse_pnpm_lock_yaml_content(PNPM_LOCK, PACKAGE_JSON, True)
    names = {d.name for d in result.deps}
    assert "jest" in names
    assert "@types/node" in names


# ---------------------------------------------------------------------------
# package.json fallback
# ---------------------------------------------------------------------------

def test_parse_package_json_fallback():
    result = _parse_package_json_content(PACKAGE_JSON, False)
    assert result.ecosystem == "npm"
    names = {d.name for d in result.deps}
    assert "express" in names
    assert "node-fetch" in names
    assert "jest" not in names
    # All should be direct
    assert all(d.is_direct for d in result.deps)


def test_parse_package_json_with_dev():
    result = _parse_package_json_content(PACKAGE_JSON, True)
    names = {d.name for d in result.deps}
    assert "jest" in names
    dev_deps = [d for d in result.deps if d.group == "dev"]
    assert any(d.name == "jest" for d in dev_deps)


# ---------------------------------------------------------------------------
# Dev filtering
# ---------------------------------------------------------------------------

def test_npm_dev_filtering():
    """include_dev=False should exclude dev dependencies."""
    result = _parse_package_lock_json_content(PACKAGE_LOCK_V2, PACKAGE_JSON, False)
    groups = {d.group for d in result.deps}
    assert "dev" not in groups


# ---------------------------------------------------------------------------
# Scoped packages
# ---------------------------------------------------------------------------

SCOPED_PACKAGE_LOCK = json.dumps({
    "lockfileVersion": 3,
    "packages": {
        "": {},
        "node_modules/@babel/core": {"version": "7.23.0"},
        "node_modules/@babel/parser": {"version": "7.23.0"},
        "node_modules/lodash": {"version": "4.17.21"},
    },
})

SCOPED_PACKAGE_JSON = json.dumps({
    "dependencies": {"@babel/core": "^7.23.0", "lodash": "^4.17.0"},
})


def test_npm_scoped_packages():
    result = _parse_package_lock_json_content(
        SCOPED_PACKAGE_LOCK, SCOPED_PACKAGE_JSON, False,
    )
    names = {d.name for d in result.deps}
    assert "@babel/core" in names
    assert "@babel/parser" in names
    assert "lodash" in names


# ---------------------------------------------------------------------------
# Priority / routing
# ---------------------------------------------------------------------------

def test_parse_npm_priority(tmp_path):
    """package-lock.json should be preferred over yarn.lock."""
    pkg_json = tmp_path / "package.json"
    pkg_json.write_text(PACKAGE_JSON)

    # Write both lockfiles
    (tmp_path / "package-lock.json").write_text(PACKAGE_LOCK_V2)
    (tmp_path / "yarn.lock").write_text(YARN_LOCK)

    result = parse_npm(tmp_path, include_dev=False)
    assert "package-lock.json" in result.source_file


def test_parse_npm_from_content():
    """Content-based entry point routes correctly."""
    bundle = {
        "package.json": PACKAGE_JSON,
        "package-lock.json": PACKAGE_LOCK_V2,
    }
    result = parse_from_content("npm", bundle, include_dev=False)
    assert result.ecosystem == "npm"
    assert len(result.deps) > 0
    assert "package-lock.json" in result.source_file


def test_parse_npm_from_content_yarn():
    """Content-based parser falls back to yarn.lock."""
    bundle = {
        "package.json": PACKAGE_JSON,
        "yarn.lock": YARN_LOCK,
    }
    result = parse_from_content("npm", bundle, include_dev=False)
    assert result.ecosystem == "npm"
    assert "yarn.lock" in result.source_file


def test_parse_npm_from_content_package_json_only():
    """Falls back to package.json when no lockfile present."""
    bundle = {"package.json": PACKAGE_JSON}
    result = parse_from_content("npm", bundle, include_dev=False)
    assert result.ecosystem == "npm"
    assert "package.json" in result.source_file
    assert len(result.deps) == 2  # express + node-fetch (no dev)
