[pytz]
module = "zoneinfo"
since = "3.9"

[tomli]
module = "tomllib"
since = "3.11"

[importlib-metadata]
module = "importlib.metadata"
since = "3.8"

[importlib-resources]
module = "importlib.resources"
since = "3.9"

[typing-extensions]
module = "typing"
since = "3.11"
partial = true

[exceptiongroup]
module = "builtins (ExceptionGroup)"
since = "3.11"

[dataclasses]
module = "dataclasses"
since = "3.7"

[contextvars]
module = "contextvars"
since = "3.7"

[mock]
module = "unittest.mock"
since = "3.3"

[pathlib2]
module = "pathlib"
since = "3.4"

[enum34]
module = "enum"
since = "3.4"

[functools32]
module = "functools"
since = "3.2"

[futures]
module = "concurrent.futures"
since = "3.2"

[configparser]
module = "configparser"
since = "3.0"

[six]
module = ""
since = "3.0"
note = "native Python 3 syntax (no single stdlib module)"

[argparse]
module = "argparse"
since = "3.2"

[async-timeout]
module = "asyncio.timeout"
since = "3.11"
